### ISSUE TITLE
ITC3 alarms tests pass, incorrectly

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#160]
The alarm tests of the ITC-3 pass, but they are not even performed?

https://github.com/rsmp-nordic/rsmp_validator/runs/5155112672?check_suite_focus=true#step:5:125

**Comment by emiltin** [comment]
rspec has a method called skip() that you can call to skip the current test. the test should then be reported as 'skipped', and not passed.
we're using the method, but inside one of our own helper methods.

we need to investigate why rspec doesn't report the tests as skipped, and fix it.

**Comment by emiltin** [comment]
example:
https://github.com/rsmp-nordic/rsmp_validator/blob/master/spec/site/tlc/alarm_spec.rb#L68

this test is reported as passed in #170, but should be reported as skipped. the test code is not actually run

**Comment by emiltin** [comment]
the problem is that rspec seems to depend on what's called thread-local storage (which is actually fiber-local). we run tests inside an aasync tasks, which is a separate fiber, and rspec therefore is missing some data,  including the current example. calling skip inside an example therefore can't set the skip flag on the current example, and thus has no effect.

a work-around is to copy the thread-local storage into our async fiber, which was implemented with 5351803. it works, the question is whether this could have any unintended side-effects. from what I can tell, it looks ok.
