### ISSUE TITLE
initial check of aggregated status / errors?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#166]
Would it make sense to do an initial check of the aggregated status, e.g. to required that no errors are present, before testing starts?

**Comment by otterdahl** [comment]
Yes, it is a generally a good idea. But it has downsides.

There is a point to not performing the tests if there are errors present, because they can prevent the tests to performed properly and thus may cause the results to be untrustworthy.

However, if the tests are manually cancelled or otherwise fails in the middle of alarm tests (for instance), then rsmp_validator may leave the TLC running with an active alarm. Next time the tests are performed it may refuse to run due to already active alarms.

This a problem with the real TLC's since they're running all the time. It may be prevented with some kind of "error reset" (or something) before the testing takes place - but it adds additional complexity and may take extra time to perform.

**Comment by emiltin** [comment]
ok. let's park this for now then
