### ISSUE TITLE
retire scripts for activating alarms?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#184]
if possible i think we should retire the use of scripts for activating alarms for testing purposeses.
it adds another layer of complexity, requires scripts to run on the testing machine.

for ITC-3 nad ITC-2 we now rely on programming in the equipment, so that activating a specific input trigges a  perticular alarm. in the future we might add rsmp commands specifically for raising alarms, e.g. for testing purposes.

**Comment by otterdahl** [comment]
I generally agree. At the moment we don't need scripts for activating alarms.

However, scripts kind of solves a problem that I don't know how we should solve otherwise.
More specifically, we have experienced issues with timestamps if alarms are activated and deactivated during comunication interruption. I think Swarco and Dynniq behaves differently in this regard. By having the ability to use scripts it is possible to activate/deactivate alarm while the RSMP connections is down. I think this type of test is useful and I don't have any other ideas how to implement this test otherwise.

**Comment by otterdahl** [comment]
> Can the TLC be programmed to raise an alarm e.g. 1 second after an input is activated? Then we can activate the input and close the connection. The alarm should then be raised while the connection is down.

Perhaps. It requires some investigation
