### ISSUE TITLE
Better warnings/errror messages

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#2]
If there is an error with the validating the format, for instance incorrect format of SXL, we only get error message "Site connection timeout".

**Comment by emiltin** [comment]
Yes that's not very informative. It's simply because logging is turned off, because in normal cases where you can connect, it's impractical to get the logging.

In case connection fails, we should output the log.

We could also think directing the rsmp loggin to a file, which you can inspect later, if you need.

**Comment by otterdahl** [comment]
It works better now. Good
