### ISSUE TITLE
input activation test assumes inputs are off

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#24]
The test first activates (forces) the input to on, and then chekcs that it's on.
It then deactivates the input, and checkes that it's off. But this check will fail if the input is actually on when testing.

I suggest removing the last check, and instead adding a test that ask the user to manually activate/deactive then physical input, and then verify this.

**Comment by otterdahl** [comment]
I'm not sure I understand. Why isn't it safe to require that the input should be off as a result of deactivating the input with M0006 status=False? Because the Input can be set to ON again by a different source?

Depending of the manufacturer, the input in M0006 is either an equivalent of the real input of the TLC (and can be set physically), or exists purely in RSMP (software)

**Comment by emiltin** [comment]
My understanding is that you can force the input, and request the status will then reflect that. Once you stop forcing the output, the value will depend on e.g .physical input. So if you expect the value to be 0, the test might fail in case the physical input is on fact 1.

**Comment by emiltin** [comment]
It was because I misunderstood how M0006 works. I though that once you stop forcing, it will jump back to the value it had before. But it doesn't.
