### ISSUE TITLE
disconnect_spec.rb: missing watchdog messages from server

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#244]
The test 'is closed if watchdogs are not received' tests if site closes down if no watchdog messages are received from server.

The RSMP specification (https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html#watchdog) does not mention anything about disconnects.

It should be explicitly stated what is expected of both client and server, when watchdog messages are missing. How many watchdogs can be missed? Should connection be closed immediately upon first missing message?

If the validator tests for it, it should be stated in the specification.

**Comment by emiltin** [comment]
@otterdahl input?

**Comment by otterdahl** [comment]
> The RSMP specification (https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html#watchdog) does not mention anything about disconnects.

Correct. But the section about Message Acknowledgment (https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html#message-acknowledgement) does.

* If no message acknowledgement is received within a predefined time, then each communicating party should treat it as a communication disruption (See [Communication disruption](https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/transport_of_data.html#communication-disruption))
* The default timeout value should be 30 seconds.

And and the watchdog section:
* The interval duration for sending watchdog messages should be configurable at both the site and the supervision system. The default setting should be (1) once a minute.

> It should be explicitly stated what is expected of both client and server, when watchdog messages are missing. How many watchdogs can be missed? Should connection be closed immediately upon first missing message?

As stated above, there is a timeout.

**Comment by sveitech** [comment]
Thank you for the clarification.

Only message acknowledgement is important when determining when to break the connection then.

**Comment by emiltin** [comment]
David, if no watchdogs are received, should the connection then be closed? It seems to be what you're implying that the spec states. However my understanding has been that if no watchdog is received, you're supposed to close the connection (the bahaviour that that the rsmp gem and the validator implements). Either way, great to get it clarified.

**Comment by otterdahl** [comment]
> David, if no watchdogs are received, should the connection then be closed? It seems to be what you're implying that the spec states.

No. Only close if no MessageAcks are received. However, Watchdog can sent to check if MessageAck are recieved. If not, then the connection is must be down. Disconnect and reconnect.

> However my understanding has been that if no watchdog is received, you're supposed to close the connection

Not quite. I don't think it is a very reliable test to expect to receive an watchdog message within a given timeout. Timeout can be set differently. Instead, we expect to receive an answer for each watchdog that we send ourself (MessageAck). If the answer is never received, than the TLC should consider this as a connection interruption.

We even specify that it must be possible to configure the watchdog interval in the specification and we don't even specify any max/min value. I think this was chosen early on in the specification since the needs can be different depending on equipment and connection type. We don't want to fill up bandwidth with pointless watchdog messages but we still want to detect communication outage.

**Comment by emiltin** [comment]
ok thanks. i'll look into adjusting the gem/validator.

**Comment by emiltin** [comment]
fixed with #262 and changes in the rsmp gem
