### ISSUE TITLE
'A0301 can be acknowledged when input is activated' uses main_component ID, but should use detector logic component ID

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#247]
According to the SXL specification (1.0.14 through 1.1) alarm A0301 belongs to the "Detector Logic" object type, but the test is using the main_component ID when sending an alarm acknowledge.

**Comment by otterdahl** [comment]
Test case for A301:
`deactivate = with_alarm_activated(task, site, alarm_code_id) do |alarm|   # raise alarm, by activating input`
Here it expects an alarm using the main component and not the detector logic, which is needed.

I suggesting extended  `alarm_activation` in  yaml config file. Right now it only contains the alarm code and input. Example:
```yaml
alarm_activation:
  A0301: 152
```
The problem is that it doesn't specify which component the alarm should have. I suggest extending this to contain this information:

```yaml
alarm_activation:
  A0301:
    input: 152
    component: KK+AG9998=001DL001
```
E.g. If Input 152 gets activated, expect alarm A0301 from component KK+AG9998=001DL001

**Comment by otterdahl** [comment]
I think this issue is quite high priority. @emiltin Have you had the chance to look into this?

**Comment by emiltin** [comment]
Not yet, but I agree that we need the component specified for input activation.
