### ISSUE TITLE
Clarification on differences between M0006 (set input) and M0019 (force input)

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#248]
What is the difference between these two command objects ?

Can input requests in M0006 be disregarded by the controller? I.E. it is a soft request rather than a force (as compared to M0019)?

**Comment by otterdahl** [comment]
* M0006 sets an input, but doesn't force it. It may change at any time due to any external source
* M0019 sets an input and forces it. It should stay in its state until unforced (with the same command)

A while ago this was discussed in https://github.com/rsmp-nordic/rsmp_implementations/issues/45 and @SwarcoPalm clarified how it works in the ITC

**Comment by sveitech** [comment]
great, thank you :)

Should the validator test perhaps be changed then? Currently it expects the input to be false again after trying to set it to false, but this depends on the configuration.

If the RSMP SXL specification does not force the input for M0006, the validator should not test for the response status.

**Comment by emiltin** [comment]
The tests first uses M0006 to set the input to True, and wait for S0003 to report that is True.
It the uses M0006 to set the input to False, and wait for S0003 to report that it is False.

Even though M0006 does not force the input, I would expect that it causes the input changes. Since it's not forced, it might be changed afterwards by another source. But unless the configuration of the TLC means it's fixed to a particular value, it should change after we send M0006?

**Comment by emiltin** [comment]
I think there a misunderstanding of what 'forcing' vs 'setting' means in this context.
When you send an M0006, the site is required to _set_ the value accordingly, meaning it must change the value. However, it's not _forced_, meaning that other source can potentially cahnge it back.

Wheras when you send an M0019, the value is _forced_, meaning that it must now be fixed, and other sources CANNOT change it. Only when you send another M0019 to unforce it, will other source be able to change it again.

Set: change the value, but don't lock it. Other can change it.
Force: change and lcok the value. Other cannot change it.

**Comment by sveitech** [comment]
Thank you for the clarification. The RSMP specification/documentation should be updated with this information.
