### ISSUE TITLE
M0004 restart - wait for command response?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#26]
The command M0004 is used for restarting the controller. The test then waits for a command response. What's the expected behaviour here? If the controller restarts immediately, it will not send a command response. Or is the controller expected to postpone restart until the command response have been send?

**Comment by emiltin** [comment]
The controller can be restarted without physical intervention from the user. But the test ask for user input before restarting the controller. Is that a safety precausion, or what's the reason?

**Comment by otterdahl** [comment]
It is not safe to restart the controller immediately, it needs to turn red in all signal groups first. This is why it waits for a command response.

Requesting input were added by me because the Swarco controller doesn't reboot the TLC unless a serious error active at the same time. This is known behavior of the Swarco TLC and we can discuss if this is correct or not. Requesting input allows the user to generate an alarm in the TLC before proceeding. I really wanted to use rsmp_validator to test the latest TLC, so this is why I added this. We can remove it if you want.

**Comment by emiltin** [comment]
So the expected behaviour is for the TLC to turn all groups to red, and then thut down? During restart, all groups will remain red, or will they turn black?

I think it's ok to require user input for certain tests, if there's a good reason. Regarding safety, these tests are not intended to be run on TLC's in service on street, but I guess as an extra precaution we can require user input.

I think the Swarco behaviour is odd, but we can discuss this. At least behaviour should be consistent across equipment, and we might need to update the spec to ensure that.

**Comment by otterdahl** [comment]
On Tue, Apr 07, 2020 at 10:23:20AM -0700, Emil Tin wrote:
> So the expected behaviour is for the TLC to turn all groups to red, and then thut down? During restart, all groups will remain red, or will they turn black?

Yes. The safe way of shutting down a TLC is to first turn red and then turn black.
It is for ensuring that all vehicles has stopped in order to avoid accidents.

The start sequence may be a little different depending of which country you're
in. In Sweden the start sequence is typically like this:

1, Yellow flashing in vehicle and bicycle signal groups for at least 5 seconds
2, Steady yellow in vehicle and bicycle signal groups for at least 5 seconds
and at the same time red in pedestrian signal groups
3, Red in all signal groups for at least 5 seconds

**Comment by emiltin** [comment]
The test now waits for a command response from the TLC. 
The Ruby TLC has been updated to match this - it first sends a command response, then restarts.
