### ISSUE TITLE
 Alarm component ID is still broken in latest master (b623506)  

### ISSUE THREAD

**Issue by FredericFlayol** [rsmp-nordic/rsmp_validator#318]
Hello, 
there  is a remaining component_id used in rspec ./spec/site/tlc/alarm_spec.rb:143 with commit # b623506 (latest version)
corresponding to this trace:
023-06-07T14:43:33.953Z  43370  KK+AG1113            KK+AG1113=001TC000   2b41  Sent Alarm  {"mType":"rSMsg","type":"Alarm","ntsOId":"","xNId":"","xACId":"","xNACId":"","aSp":"Resume","cId":"KK+AG1113=001TC000","aCId":"A0302","mId":"2b416f75-ca4d-4303-a3b8-106ea350201d"}
used in Alarm test rspec ./spec/site/tlc/alarm_spec.rb:143 # Site::Traffic Light Controller Alarm A0302 can be suspended and resumed

    it 'A0302 can be suspended and resumed' do
      Validator::Site.connected do |task,supervisor,site|
        alarm_code = 'A0302'
        **component_id = Validator.config['main_component']**
        # first resume to make sure something happens when we suspend
        resume = RSMP::AlarmResume.new(
          'cId' => component_id,
          'aCId' => alarm_code
        )
        site.send_message resume

Thank you for your help,

**Comment by emiltin** [comment]
Hi, thank you for reporting this. Yes, it should use a component configured for testing alarm suspension, rather than the main component.

**Comment by emiltin** [comment]
PR #320 fixes this. the test config for alarm testing has been a little reorganized and looks like this:
```yaml
alarms:
  A0302: 
    activation_input: 7
    component: DL1
```

This config is used for both the test `A0302 can be acknowledged` and `A0302 can be suspended and resumed`, because they both uses A302 for the test.

I think it's important that the alarm used (A0302) is defined in test test, and not in the config. But the component must be configurable, because it depends on the setup in the device. Since both tests use A0302 I think it makes most sense that you configure A0302 once for both tests, and both tests will use the same component id.

**Comment by emiltin** [comment]
fixed in master. feel fre to reopen this issue if needed
