### ISSUE TITLE
Command tests fail due to not getting status updates

### ISSUE THREAD

**Issue by GunnarRolander** [rsmp-nordic/rsmp_validator#32]
A number of the command tests fail when running the verify_status() function, with the following error message (of course with varying statuc codes):
`Did not receive status {"sCI"=>"S0015", "n"=>"status", "s"=>"1"}`

It's the tests for command M0003 (missing status S0015), M0005 (missing S0006) and M0006 (missing S0003).

I can't determine if the tests are working as intended and it's the equipment that fails, or if the tests are faulty.
It seems like the verify_status() function is getting the expected responses in other test cases, such as the tests of M0001 and M0002, hence my uncertainty as to where the error is located.

**Comment by emiltin** [comment]
You can try inspecting look at message log to see if the message is received.

**Comment by otterdahl** [comment]
Looking at the [log file](https://otterdahl.org/rsmp_validator_log/validation-2020-10-20_18-35-29.log) (validation-2020-10-20_18-35-29.log) I can see the following:

The M0003 test fails due to S0015 never switches to the expected value. The M0003 sets the traffic situation, but the test simulator is currently not configured to have any traffic situation.

The test case M0003 tries to switch to traffic situation '1' using a CommandRequest. The test simulator answers with CommandResponse set to '1' - which indicates that the simulator has accepted the request. The test case then subscribes to S0015 to check that the traffic situation indeed has changed, but that never happens, it always reports that the current traffic situation is '0'.

I believe that the same goes for the M0005 the case. No emergency routes are configured in the test simulator.

The M0006 test needs further investigation. Since this test simulator is actually based on Swarco controller, I believe that the input '1' actually activates input '101' (+100) in the S0003 status, but I think this is configurable.

**Comment by otterdahl** [comment]
Commit 4db2428f28ce1c58f21b90e268b794357ab60dec fixes "M0007 set fixed time"

**Comment by otterdahl** [comment]
Commit 13dd5cc8a7ee309e3ed94d08d6d9cf997e9a910d fixes "M0006". It now reads inputs to test from config file.

I'm closing this issue because I believe that all failures are explained. Feel free to open this issue again if there are more questions.
