### ISSUE TITLE
invalid_command_spec.rb, test 'returns a command response with age=undefined' should not run for core 3.1.2

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#345]
The ageState=undefined was introduced in core 3.1.3 (https://rsmp-nordic.github.io/rsmp_specifications/core/3.1.3/applicability/basic_structure.html#command-messages). The test should be limited to core 3.1.3 and above.

**Comment by emiltin** [comment]
Fixed with #346.
Note that you need to set the core version in the test config before this has any effect - the filterering is done against the version set in the test config, not what the equipment reports when connecting, eg in `swarco_itc3.yaml`:

```yaml
restrict_testing:
  core_version: 3.1.2
  sxl_version: 1.0.13
```

This should reflect the versions that the equipment runs. It's done this way to avoid faulty equipment affecting what tests are run.

**Comment by sveitech** [comment]
This is what I have in the config:

restrict_testing:
  core_version: 3.1.5
  sxl_version: 1.0.13

**Comment by emiltin** [comment]
As long as that reflects what the equipment runs, that should be ok.
