### ISSUE TITLE
signal_groups_spec: "follows startup sequence after restart" is problematic

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#353]
If I understand this test correctly, it restarts the device, then waits for the startup sequence, then waiting for ready.

This is problematic for a number of reasons:

1. Swarco devices will not (as mentioned before) support a device restart feature.
2. There is no guarantee that RSMP will connect to the server, before the controller is running through the startup program.
3. There is no requirement in the RSMP spec, that a controller should wait for a RSMP server connection, before running a startup sequence.
4. Such a requirement would cause unconnected devices to remain dark, if they had to wait for the server berfore starting the traffic controller.

The test is meaningless for any real-world applications. A traffic controller will start up as soon as possible after a restart/failure, regardless of any additional applications on the device, networked or not.

**Comment by emiltin** [comment]
Thank you for the input.
The intention is to be able to check the startup sequence. Do you have suggestions how we can do that?

**Comment by sveitech** [comment]
You already have a test for this: 'follow startup sequence after yellow flash', which works fine.

**Comment by emiltin** [comment]
Good point. Are the two sequences always the same?

**Comment by sveitech** [comment]
The startup sequence depends on the controller configuration. I suspect they can be different? but unlikely. 

I have mentioned this before, but will do so again: I believe this kind of testing is far beyond the scope of the RSMP protocol validator. You are trying to test specific controller operations. Not RSMP protocol messages.

The RSMP protocol does not have a specification for "startup sequence". It is a terminology used by traffic controllers. As the RSMP protocol does not have a specification for it, I do not believe that the validator should test for it.

The validator is expecting a particular pattern given by the S0001 object. There is no specification on how S0001 should behave, only that it should supply the current group states. If you write tests for particular sequences, you need to write this into the spec of S0001, that S0001 should be able to supply particular sequences, with particular timing, when given specific commands (e.g. restart command).

**Comment by emiltin** [comment]
It's an important discussion, and I agree that it makes sense to distinguish between protocol and functional tests.
As mentioned in #224, we agree that the main focus of the RSMP Validator is protocol testing. But the validator can also be used for functional testing, which is why we've added a few to test the waters. We see a big potential for also testing functional aspect. As you state, such functional behaviour can differ between countries, and would require additional test configuration to reflect this.

For now we're clearly tagging the (few) functional tests, so they can easily be excluded if desired.

For the concrete test 'follows startup sequence after restart', it's a valid point that restart is problematic. I think the best might be to just rely on 'follow startup sequence after yellow flash' and remove the startup test.

**Comment by emiltin** [comment]
@david, to you agree with removing the 'follows startup sequence after restart'? We still have 'follow startup sequence after yellow flash'.
Since not all controllers implement restart (and we make the restart command optional or change it to a reset), i think it makes sense.

**Comment by SwarcoPalm** [comment]
Even for the controllers that do implement reboot, this test might still not work correctly, because depending on how fast RSMP is started and reconnects to the validator, you might already have missed the first part of the startup sequence.

There's no guarantees that the RSMP connection is up and running before the controller starts up. Doing it via yellow flash or some other method is a more robust way to test this.

**Comment by otterdahl** [comment]
Yes. I think this test can be removed due to the reasons stated.

**Comment by emiltin** [comment]
The test "follows startup sequence after restart" has been removed. We instead rely on "follow startup sequence after yellow flash". That test is tagged with `:functional`.

**Comment by emiltin** [comment]
Fixed with #365
