### ISSUE TITLE
How to change SXL version?

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#5]
rsmp_validator sends SXL version 1.1. But version 1.0.7 or later is needed to succssfully connect. How do I change it?

**Comment by emiltin** [comment]
With 7a5dac9, the supervisor will store the sxl version received from the site, and return it when sending the Version message. Should fix your problem, without the need to manually set the SXL.

Note: For sites (when you test a supervisor) you can now manually set the SXL version when you use the TestSupervisor helper class. Problably not relevant at the moment, since your testing sites currently.

**Comment by otterdahl** [comment]
The latest commit seems to fix the problem
