### ISSUE TITLE
Question about status request

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#7]
When testing status and looking at `spec/site/status_spec.rb` my guess is  that "1234" is the expected response of the status request.
```
     copy = response.attributes["sS"].dup
     copy.each do |sS|
       sS["s"] = "1234" if sS["s"]
     end
     expect(copy).to eq( [{"n"=>status_name, "q"=>"recent", "sCI"=>status_code, "s"=>"1234"}] )
```
I know that I get a different response, but still I get the following output:
```
Finished in 1.11 seconds (files took 0.31967 seconds to load)
1 example, 0 failures
```

It looks like it was successful? How do I fix the response check?

**Comment by emiltin** [comment]
The spec was written to test a Ruby RSMP site. A Ruby RSMP site sends a random value when you request a status. The value '1234' is written into a copy of the response with ```sS["s"] = "1234"```, so that expect() can check against a known value. Yeah it's a bit akward.

If you know the value you expect, you can simplify the code above to eg:
```ruby
expect(response.attributes["sS"]).to eq( [{"n"=>status_name, "q"=>"recent", "sCI"=>status_code, "s"=>"100"}] )
```

**Comment by otterdahl** [comment]
Ok. I think I understand. Closing the issue
