### ISSUE TITLE
Circumvent known problems?

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#99]
With tools such as `netsed` it is possible in real time to alter the contents of packets forwarded in a network stream.
This makes it possible to circumvent certain issues with the controllers not passing the json schema when connected to GitHub actions.

For instance, it is possible to circumvent this issue with the ITC-2: https://github.com/rsmp-nordic/rsmp_implementations/issues/8 by simply modifying the workflow file for the ITC-2

Is this a good idea? Or could it give the wrong impression? The best solution is of course to fix the problem at it's source. But at the same time it is desirable to continue working on the test cases without having schema issues affecting multiple test cases.

**Comment by emiltin** [comment]
While I understand the intention, I don't think it's a good idea. I think it would obscure bugs and complicate our setup.

A failing test is a good thing, because it points to a bug in the implementation. In cases like the one with ITC-2 where a site keeps sending messages with invalid schemas it's true that our current handling causes a lot of tests to abort early. Perhaps the question is how we best capture these invalid alarms. Aborting the current test is one way to surface the issue. But we could think of other ways, like just printing a warning in the test log instead of aborting the current test.

I think modifying packets with e.g. `netsed` would increase the complexity of our tests setup and make debugging problems with the test suite itself much harder.

**Comment by otterdahl** [comment]
I totalt agree. I just wanted a second option.
